[package]
name = "smolecho"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
assert_cmd = "2.0.17"
clap = { version = "4.5.40", features = ["derive"] }
predicates = "3.1.3"
pretty_assertions = "1.4.1"
